control_gateway:
  ros__parameters:
    joy_topic: "/joy"
    selector_topic: "/control_selector"
    drive_topic: "/drive"
    manual_auto_swap_topic: "/control_gateway/switch_manual_auto"
    default_controller: "pure_pursuit"

    enable_button_index: 4
